export default interface User {
    id: string,
    Agilité_base: number,
    Agilité_bonus: number
    Agilité_total: number,
    Chance_base: number,
    Chance_bonus: number,
    Chance_total: number,
    'Cote Kolizeum'?: number,
    'Cote Kolizeum 3v3 solo'?: number,
    'Cote Kolizeum 3v3 équipe'?: number,
    Critique_base: number,
    Critique_bonus: number,
    Critique_total: number,
    'Esquive PA_base': number,
    'Esquive PA_bonus': number,
    'Esquive PA_total': number,
    'Esquive PM_base': number,
    Force_base: number,
    Force_bonus: number,
    Force_total: number,
    Fuite_base: number,
    Fuite_bonus: number,
    Fuite_total: number,
    Initiative_base: number,
    Initiative_bonus: number,
    Initiative_total: number,
    Intelligence_base: number,
    Intelligence_bonus: number,
    Intelligence_total: number,
    Invocation_base: number,
    Invocation_bonus: number,
    Invocation_total: number,
    "Points d'action (PA)_base": number,
    "Points d'action (PA)_bonus": number,
    "Points d'action (PA)_total": number,
    "Points de mouvement (PM)_base": number,
    "Points de mouvement (PM)_bonus": number,
    "Points de mouvement (PM)_total": number,
    Portée_base: number,
    Portée_bonus: number,
    Portée_total: number,
    Prospection_base: number,
    Prospection_bonus: number,
    Prospection_total: number,
    Puissance_base: number,
    Puissance_bonus: number,
    Puissance_total: number,
    "Retrait PA_base": number,
    "Retrait PA_bonus": number,
    "Retrait PA_total": number,
    "Retrait PM_base": number,
    "Retrait PM_bonus": number,
    "Retrait PM_total": number,
    Sagesse_base: number,
    Sagesse_bonus: number,
    Sagesse_total: number,
    Soins_base: number,
    Soins_bonus: number,
    Soins_total: number,
    Tacle_base: number,
    Tacle_bonus: number,
    Tacle_total: number,
    Vitalité_base: number,
    Vitalité_bonus: number,
    Vitalité_total: number,
    amulet?: number,
    belt?: number,
    boots?: number,
    cap?: number,
    "do_Air (fixe)_total": number,
    "do_Dommages critiques_total": number,
    "do_Dommages_total": number,
    "do_Eau (fixe)_total": number,
    "do_Feu (fixe)_total": number,
    "do_Neutre (fixe)_total": number,
    "do_Pièges (Puissance)_total": number,
    "do_Pièges (fixe)_total": number,
    "do_Poussée_total": number,
    "do_Renvoi_total": number,
    "do_Terre (fixe)_total": number,
    "dofus-0"?: number,
    "dofus-1"?: number,
    "dofus-2"?: number,
    "dofus-3"?: number,
    "dofus-4"?: number,
    "dofus-5"?: number,
    hat?: number,
    koli_breed_rk?: number,
    koli_breed_server_rk?: number,
    koli_general_rk?: number,
    koli_server_rk?: number,
    level: number,
    name: string,
    pet?: number,
    "res_Air (%)_total": number,
    "res_Air (fixe)_total": number,
    "res_Coups critiques (fixe)_total": number,
    "res_Eau (%)_total": number,
    "res_Eau (fixe)_total": number,
    "res_Feu (%)_total": number,
    "res_Feu (fixe)_total": number,
    "res_Neutre (%)_total": number,
    "res_Neutre (fixe)_total": number,
    "res_Poussée (fixe)_total": number,
    "res_Terre (%)_total": number,
    "res_Terre (fixe)_total": number,
    ring1?: number,
    ring2?: number,
    shield?: number,
    success?: number,
    success_breed_rk?: number,
    success_breed_server_rk?: number,
    success_general_rk?: number,
    success_server_rk?: number,
    weapon?: number,
    xp: number,
    xp_breed_rk?: number,
    xp_breed_server_rk?: number,
    xp_general_rk?: number,
    xp_server_rk?: number,
}

export const UserFields = {
    id: 'Id',
    level: 'Level',
    Chance_base: 'Chance Base',
    Chance_bonus: 'Chance Bonus',
    Chance_total: 'Chance Total',
}
